steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '-t'
      - 'gcr.io/$PROJECT_ID/it-user-service:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/it-user-service:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/it-user-service:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/it-user-service:latest'

  # Substitute variables in deployment files
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sed -e 's/\$$PROJECT_ID/'$PROJECT_ID'/g' -e 's/\$$COMMIT_SHA/'$COMMIT_SHA'/g' deploy/cloudrun-staging.yaml > deploy/cloudrun-staging-processed.yaml
        sed -e 's/\$$PROJECT_ID/'$PROJECT_ID'/g' -e 's/\$$COMMIT_SHA/'$COMMIT_SHA'/g' deploy/cloudrun-production.yaml > deploy/cloudrun-production-processed.yaml
    id: 'substitute-vars'

  # Deploy to Cloud Run Staging (only on develop branch)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'services'
      - 'replace'
      - 'deploy/cloudrun-staging-processed.yaml'
      - '--region=us-east1'
      - '--project=$PROJECT_ID'
    waitFor: ['substitute-vars']
    id: 'deploy-staging'

  # Deploy to Cloud Run Production (only on main branch)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'services'
      - 'replace'
      - 'deploy/cloudrun-production-processed.yaml'
      - '--region=us-east1'
      - '--project=$PROJECT_ID'
    waitFor: ['substitute-vars']
    id: 'deploy-production'

# Substitute variables in deployment files
substitutions:
  _REGION: 'us-east1'
  _PROJECT_ID: '$PROJECT_ID'

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/it-user-service:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/it-user-service:latest'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  # machineType: 'E2_HIGHCPU_8'

# Build timeout
timeout: '1200s'