version: '3.8'

services:
  # Aplicación para testing
  app-test:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=test
    env_file:
      - .env.test
    depends_on:
      - postgres-test
    networks:
      - test-network
    restart: "no"

  # Base de datos para testing
  postgres-test:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: microservice_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./scripts/init-test.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - test-network
    restart: "no"

  # Contenedor para ejecutar tests
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - postgres-test
    networks:
      - test-network
    command: ["go", "test", "./...", "-v"]

networks:
  test-network:
    driver: bridge