apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: it-user-service
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "100"
        autoscaling.knative.dev/minScale: "2"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      containers:
      - image: gcr.io/$PROJECT_ID/it-user-service:$COMMIT_SHA
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "warn"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: latest
              name: it-chatbot-jwt-password
        - name: DB_HOST
          value: "35.227.10.150"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "it_db_chatbot"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: latest
              name: it-chatbot-db-password
        resources:
          limits:
            cpu: "2"
            memory: "1Gi"
          requests:
            cpu: "1"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10